\chapter{Catching Exceptions\label{chap:CatchingExceptions}}

Catchers can be used to process thrown exceptions.
ASL allows specifying a list of \emph{catch clauses}.
Each catch clause starts with the \Twhen{} keyword,
and specifies when an exception
should be caught (based on its type), and a statement to be executed
when an exception has been caught.
A final optional \Totherwise{} clause
catches all exceptions that have not been caught
by a preceding catch clause.

\ExampleDef{Exception Catchers}
\listingref{CatchingExceptions} shows examples of catching exceptions.
\ASLListing{Catching exceptions}{CatchingExceptions}{\definitiontests/CatchingExceptions.asl}

\listingref{CatchingExceptions2} shows more examples of throwing and catching exceptions.
The exception \verb|BAD_OPCODE| thrown in \verb|decode_instruction| is caught in the calling
subprogram \verb|top| where the catcher proceeds to call \verb|handle_exception|.
\ASLListing{Catching exceptions}{CatchingExceptions2}{\definitiontests/CatchingExceptions2.asl}

\ChapterOutline
\begin{itemize}
  \item \FormalRelationsRef{Exception Catchers} defines the formal relations for exception catchers;
  \item \SyntaxRef{Exception Catchers} defines the syntax of exception catchers;
  \item \AbstractSyntaxRef{Exception Catchers} defines the abstract syntax of exception catchers;
  \item \TypeRulesRef{Exception Catchers} defines the type rules for exception catchers;
  \item \SemanticsRulesRef{Exception Catchers} defines the dynamic semantics of exception catchers.
\end{itemize}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\FormalRelationsDef{Exception Catchers}
\paragraph{Syntax:} Exception catchers are grammatically derived from $\Ncatcher$.
\paragraph{Abstract Syntax:} Exception catchers are derived in the abstract syntax by $\catcher$
  and generated using $\buildcatcher$.
\paragraph{Typing:} Exception catchers are annotated by $\annotatecatcher$.
\paragraph{Semantics:} Exception catchers are evaluated via $\evalcatchers$.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\SyntaxDef{Exception Catchers}
\begin{flalign*}
\Ncatcher \derives      \ & \Twhen \parsesep \Tidentifier \parsesep \Tcolon \parsesep \Nty \parsesep \Tarrow \parsesep \Nstmtlist &\\
          |\              & \Twhen \parsesep \Nty \parsesep \Tarrow \parsesep \Nstmtlist &\\
\end{flalign*}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\AbstractSyntaxDef{Exception Catchers}
\RenderType[remove_hypertargets]{catcher}

\ASTRuleDef{Catcher}
\MarkedIgnoredRelationDefinition{
\hypertarget{build-catcher}{}
The function
\[
\buildcatcher(\overname{\parsenode{\Ncatcher}}{\vparsednode}) \;\aslto\; \overname{\catcher}{\vastnode}
\]
transforms a parse node $\vparsednode$ into an AST node $\vastnode$.
} % END_OF_IGNORED_RELATION


\begin{mathpar}
\inferrule[named]{}{
  {
  \begin{array}{r}
  \buildcatcher(\overname{\Ncatcher(\Twhen, \Tidentifier(\id), \Tcolon, \Nty, \Tarrow, \Nstmtlist)}{\vparsednode})
  \astarrow \\
  \overname{(\some{\id}, \astof{\tty}, \astof{\vstmtlist})}{\vastnode}
  \end{array}
  }
}
\end{mathpar}

\begin{mathpar}
\inferrule[unnamed]{}{
  {
  \begin{array}{r}
  \buildcatcher(\overname{\Ncatcher(\Twhen, \Nty, \Tarrow, \Nstmtlist)}{\vparsednode})
  \astarrow \\
  \overname{(\None, \astof{\tty}, \astof{\vstmtlist})}{\vastnode}
  \end{array}
  }
}
\end{mathpar}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\TypeRulesDef{Exception Catchers}
\RenderRelation{annotate_catcher}
\BackupOriginalRelation{
The function
\[
\begin{array}{r}
  \annotatecatcher(
    \overname{\staticenvs}{\tenv} \aslsep
    \overname{\TSideEffectSet}{\vsesin} \aslsep
    \overname{\catcher}{\vc}
  ) \aslto \\
  (\overname{\TSideEffectSet}{\vsesin} \times (\overname{\catcher}{\newcatcher}, \overname{\TSideEffectSet}{\vses}))
  \cup \overname{\typeerror}{\TypeErrorConfig}
\end{array}
\]
annotates a catcher $\vc$ in the \staticenvironmentterm{} $\tenv$
and \sideeffectsetterm\ $\vsesin$.
The result is the \sideeffectsetterm\ $\vsesin$, the annotated catcher $\newcatcher$ and the
\sideeffectsetterm\ $\vses$.
\ProseOtherwiseTypeError
} % END_OF_BACKUP_RELATION

\TypingRuleDef{Catcher}
\ExampleDef{Annotating Catch Clauses}
\listingref{annotate-catcher} shows a \trystatementterm{}
with catch clauses for unnamed exception values for the exception types \verb|ExceptionType1| and \verb|ExceptionType3|,
and a catch clause for the named exception value for the exception type \verb|ExceptionType2|.
\ASLListing{Annotating catch clauses}{annotate-catcher}{\typingtests/TypingRule.Catcher.asl}

\ProseParagraph
\OneApplies
\begin{itemize}
  \item \AllApplyCase{none}
  \begin{itemize}
    \item the catcher has no named identifier, that is, $\vc$ is $(\overname{\None}{\nameopt}, \tty, \vstmt)$;
    \item annotating the type $\tty$ in $\tenv$ yields $(\ttyp, \vsesty)$\ProseOrTypeError;
    \item determining whether $\ttyp$ has the \structureterm\ of an exception type yields \\ $\True$\ProseOrTypeError;
    \item annotating the block $\vstmt$ in $\tenv$ yields $\newstmt$;
    \item \Proseeqdef{$\newcatcher$}{$(\overname{\None}{\nameopt}, \ttyp, \newstmt)$};
  \end{itemize}

  \item \AllApplyCase{some}
  \begin{itemize}
    \item the catcher has a named identifier, that is, $\vc$ is $(\some{\name}, \tty, \vstmt)$;
    \item annotating the type $\tty$ in $\tenv$ yields $(\ttyp, \vsesty)$\ProseOrTypeError;
    \item determining whether $\ttyp$ has the \structureterm\ of an exception type yields \\ $\True$\ProseOrTypeError;
    \item the identifier $\name$ is not bound in $\tenv$;
    \item binding $\name$ in the local environment of $\tenv$ with the type $\ttyp$ as an immutable variable
          (that is, with the local declaration keyword $\LDKLet$), yields the \staticenvironmentterm{} $\tenvp$;
    \item annotating the block $\vstmt$ in $\tenvp$ yields $(\newstmt, \vsesblock)$;
    \item \Proseeqdef{$\newcatcher$}{$(\overname{\some{\name}}{\nameopt}, \ttyp, \newstmt)$};
  \end{itemize}
  \item \Proseeqdef{$\vses$}{the union of $\vsesblock$ and $\vsesty$}.
\end{itemize}

\FormallyParagraph
\begin{mathpar}
\inferrule[none]{
  \vc = (\overname{\None}{\nameopt}, \tty, \vstmt)\\
  \annotatetype(\tenv, \vt) \typearrow (\ttyp, \vsesty) \OrTypeError\\\\
  \checkstructurelabel(\tenv, \ttyp, \TException) \typearrow \True \OrTypeError\\\\
  \annotateblock(\tenv, \vstmt) \typearrow (\newstmt, \vsesblock) \OrTypeError\\\\
  \newcatcher \eqdef (\overname{\None}{\nameopt}, \ttyp, \newstmt)\\\\
  \commonsuffixline\\\\
  \vses \eqdef \vsesblock \cup \vsesty\\
}{
  \annotatecatcher(\tenv, \vsesin, \vc) \typearrow (\vsesin, \newcatcher, \vses)
}
\end{mathpar}
\CodeSubsection{\CatcherNoneBegin}{\CatcherNoneEnd}{../Typing.ml}
\identr{SDJK}

\begin{mathpar}
\inferrule[some]{
  \vc = (\overname{\some{\name}}{\nameopt}, \tty, \vstmt)\\
  \annotatetype(\tenv, \vt) \typearrow (\ttyp, \vsesty) \OrTypeError\\\\
  \checkstructurelabel(\tenv, \ttyp, \TException) \typearrow \True \OrTypeError\\\\
  \checkvarnotinenv(\tenv, \name) \typearrow \True \OrTypeError\\\\
  \addlocal(\tenv, \name, \ttyp, \LDKLet) \typearrow \tenvp\\
  \annotateblock(\tenvp, \vstmt) \typearrow (\newstmt, \vsesblock) \OrTypeError\\\\
  \newcatcher \eqdef (\overname{\some{\name}}{\nameopt}, \ttyp, \newstmt)\\\\
  \commonsuffixline\\\\
  \vses \eqdef \vsesblock \cup \vsesty\\
}{
  \annotatecatcher(\tenv, \vsesin, \vc) \typearrow (\vsesin, \newcatcher, \vses)
}
\end{mathpar}

\CodeSubsection{\CatcherBegin}{\CatcherEnd}{../Typing.ml}
\identr{SDJK} \identr{WVXS} \identi{FCGK}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\SemanticsRulesDef{Exception Catchers}
The semantic relation for evaluating catchers employs an argument
that is an output configuration. This argument corresponds to the result
of evaluating a \trystatementterm{} and its type is defined as follows:
\RenderType{TOutConfig}
\BackupOriginalType{
\[
  \TOutConfig \triangleq \TNormal \cup  \TThrowing \cup \TContinuing \cup \TReturning \enspace.
\]
} % END_OF_BACKUP_TYPE

\RenderRelation{eval_catchers}
\BackupOriginalRelation{
The relation
\[
  \evalcatchers(\overname{\envs}{\env} \aslsep \overname{\KleeneStar{\catcher}}{\catchers} \aslsep \overname{\Option{\stmt}}{\otherwiseopt}
   \aslsep \overname{\TOutConfig}{\sm}) \;\aslrel\;
  \left(
    \begin{array}{cl}
      \TReturning   & \cup\\
      \TContinuing  & \cup\\
      \TThrowing    & \cup \\
      \TDynError       &
    \end{array}
  \right)
\]
evaluates a list of \texttt{catch} clauses $\catchers$, an optional \texttt{otherwise} clause,
and a configuration $\sm$ resulting from the evaluation of the throwing expression,
in the environment $\env$. The result --- $\smnew$ --- is either a continuation configuration,
an early return configuration, or an abnormal configuration.
} % END_OF_BACKUP_RELATION

We refer to the block statement in a
\trystatementterm{} as the \emph{try-block statement}.
When the try-block statement is evaluated, it may call a function that updates
the global environment. If evaluation of the \texttt{try} block raises an exception that is caught,
either by a \texttt{catch} clause or an \texttt{otherwise} clause,
the statement associated with that clause, which we will refer to as the clause statement, is evaluated.
It is important to evaluate the clause statement in an environment that includes any updates
to the global environment made by evaluating the try-block statement.
%
We demonstrate this with the following example.

\ExampleDef{Evaluating a Try Statement}
In \listingref{semantics-evalcatchers}, the statement \verb|update_and_throw();|
makes up the whole try-block.
Evaluating the call to \verb|update_and_throw| employs an environment $\env$ where
\texttt{g} is bound to $0$.
Notice that the call to \verb|update_and_throw| binds \texttt{g} to $1$ before raising an exception.
Therefore, evaluating the call to \verb|update_and_throw| returns a configuration
of the form
$\Throwing(\Ignore, \Ignore, \Ignore, \envthrow)$ where $\envthrow$ binds \texttt{g} to $1$.
When the catch clause is evaluated the semantics takes the global environment from $\envthrow$
to account for the update to \texttt{g} and the local environment from $\env$ to account for the
updates to the local environment in \texttt{main}, which binds \texttt{x} to $2$, and use this
environment to evaluate \texttt{print(x, g)}, resulting in the output \texttt{2 1}.

\ASLListing{Semantics of exception catching}{semantics-evalcatchers}{\semanticstests/EvalCatchers.asl}

\SemanticsRuleDef{Catch}
\ExampleDef{Evaluation of a Catch}
The specification in \listingref{semantics-catch} terminates successfully.
That is, no \dynamicerrorterm{} occurs.
\ASLListing{Catching an exception}{semantics-catch}{\semanticstests/SemanticsRule.Catch.asl}

\ProseParagraph
\AllApply
\begin{itemize}
  \item $\sm$ is $\Throwing(\vv, \vvty, \sg, \envthrow)$;
  \item $\env$ consists of the \staticenvironmentterm{} $\tenv$ and dynamic environment $\denv$;
  \item $\envthrow$ consists of the \staticenvironmentterm{} $\tenv$ and dynamic environment \\ $\denvthrow$;
  \item finding the first catcher with the \staticenvironmentterm{} $\tenv$, the exception type $\vvty$,
        and the list of catchers $\catchers$ gives a catcher that does not declare a name ($\None$) and gives a statement $\vs$;
  \item evaluating $\vs$ in $\envthrow$ as a block (\SemanticsRuleRef{Block}) yields a (non-error)
        configuration $C$\ProseOrDynErrorDiverging;
  \item $\newg$ is the ordered composition of $\sg$ and the graph of $C$;
  \item the result of the entire evaluation is $C$ with its graph substituted with $\newg$.
\end{itemize}

\FormallyParagraph
\begin{mathpar}
\inferrule{
  \sm \eqname \Throwing(\vv, \vvty, \sg, \envthrow)\\
  \env \eqname (\tenv, (G^\denv, L^\denv))\\
  \envthrow \eqname (\tenv, (G^{\denvthrow}, L^{\denvthrow}))\\
  \findcatcher(\tenv, \vvty, \catchers) \eqname \some{ (\None, \Ignore, \vs) }\\
  \evalblock(\envthrow, \vs) \evalarrow C \OrDynErrorDiverging\\\\
  \newg \eqdef \ordered{\sg}{\aslpo}{\graphof{C}}
}{
  \evalcatchers(\env, \catchers, \otherwiseopt, \sm) \evalarrow \withgraph{C}{\newg}
}
\end{mathpar}
\CodeSubsection{\EvalCatchBegin}{\EvalCatchEnd}{../Interpreter.ml}

\SemanticsRuleDef{CatchNamed}
\ExampleDef{Catching a Named Exception}
The specification in \listingref{semantics-catchnamed}, prints \texttt{My exception with my message}.
\ASLListing{Catching a named exception}{semantics-catchnamed}{\semanticstests/SemanticsRule.CatchNamed.asl}

\ProseParagraph
\AllApply
\begin{itemize}
  \item $\sm$ is $\Throwing(\vv, \vvty, \sg, \envthrow)$;
  \item $\env$ consists of the \staticenvironmentterm{} $\tenv$ and dynamic environment $\denv$;
  \item $\envthrow$ consists of the \staticenvironmentterm{} $\tenv$ and dynamic environment \\ $\denvthrow$;
  \item finding the first catcher with the \staticenvironmentterm{} $\tenv$, the exception type $\vvty$,
  and the list of catchers $\catchers$ gives a catcher that declares the name $\name$ and gives a statement $\vs$;
  \item applying $\readvaluefrom$ to $\vv$ yields $(\vv, \vgone)$;
  \item declaring a local identifier $\name$ with $(\vv, \vgone)$ in $\envthrow$ gives $(\envtwo, \vgtwo)$;
  \item evaluating $\vs$ in $\envtwo$ as a block (\SemanticsRuleRef{Block}) is not an error
        configuration $C$\ProseOrDynErrorDiverging;
  \item $\envthree$ is the environment of the configuration $C$;
  \item removing the binding for $\name$ from the local component of the dynamic environment in $\envthree$
        gives $\envfour$;
  \item substituting the environment of $C$ with $\envfour$ gives $D$;
  \item $\newg$ is the ordered composition of $\sg$, $\vgone$, $\vgtwo$, and the graph of $D$,
        with the $\aslpo$ edges;
  \item the result of the entire evaluation is $D$ with its graph substituted with $\newg$.
\end{itemize}
\FormallyParagraph
\begin{mathpar}
\inferrule{
  \sm \eqname \Throwing(\vv, \vvty, \sg, \envthrow)\\
  \env \eqname (\tenv, (G^\denv, L^\denv))\\
  \envthrow \eqname (\tenv, (G^{\denvthrow}, L^{\denvthrow}))\\
  \findcatcher(\tenv, \vvty, \catchers) \eqname \some{ (\some{\name}, \Ignore, \vs) }\\
  \readvaluefrom(\vv) \evalarrow (\vv, \vgone)\\
  \declarelocalidentifierm(\envthrow, \name, (\vv, \vgone)) \evalarrow (\envtwo, \vgtwo)\\
  \evalblock(\envtwo, \vs) \evalarrow C \OrDynErrorDiverging\\\\
  \envthree \eqdef \environof{C}\\
  \removelocal(\envthree, \name) \evalarrow \envfour\\
  D \eqdef \withenviron{C}{\envfour}\\
  \newg \eqdef \ordered{\sg}{\aslpo}{ \ordered{\ordered{\vgone}{\aslpo}{\vgtwo}}{\aslpo}{\graphof{D}} }
}{
  \evalcatchers(\env, \catchers, \otherwiseopt, \sm) \evalarrow \withgraph{D}{\newg}
}
\end{mathpar}
\CodeSubsection{\EvalCatchNamedBegin}{\EvalCatchNamedEnd}{../Interpreter.ml}

\SemanticsRuleDef{CatchOtherwise}
\ExampleDef{Evaluation of a Catch with an Otherwise}
The specification in \listingref{semantics-catchotherwise} prints \texttt{Otherwise}.
\ASLListing{Catching an exception with \texttt{otherwise}}{semantics-catchotherwise}{\semanticstests/SemanticsRule.CatchOtherwise.asl}

\ProseParagraph
\AllApply
\begin{itemize}
  \item $\sm$ is $\Throwing(\vv, \vvty, \sg, \envthrow)$;
  \item $\env$ consists of the \staticenvironmentterm{} $\tenv$ and dynamic environment $\denv$;
  \item $\envthrow$ consists of the \staticenvironmentterm{} $\tenv$ and dynamic environment \\ $\denvthrow$;
  \item finding the first catcher with the \staticenvironmentterm{} $\tenv$, the exception type $\vvty$,
        and the list of catchers $\catchers$ gives a catcher that declares the name $\name$ and gives $\None$
        (that is, neither of the \texttt{catch} clauses matches the raised exception);
  \item evaluating the \texttt{otherwise} statement $\vs$ in $\envtwo$ as a block (\SemanticsRuleRef{Block})
        is not an error configuration $C$\ProseOrDynErrorDiverging;
  \item $\newg$ is the ordered composition of $\sg$ and the graph of $C$,
        with the $\aslpo$ edge;
  \item the result of the entire evaluation is $C$ with its graph substituted with $\newg$.
\end{itemize}

\FormallyParagraph
\begin{mathpar}
\inferrule{
  \sm \eqname \Throwing(\vv, \vvty, \sg, \envthrow)\\
  \env \eqname (\tenv, (G^\denv, L^\denv))\\
  \envthrow \eqname (\tenv, (G^{\denvthrow}, L^{\denvthrow}))\\
  \findcatcher(\tenv, \vvty, \catchers) = \None\\
  \evalblock(\envthrow, \vs) \evalarrow C \OrDynErrorDiverging\\\\
  \vg \eqdef \ordered{\sg}{\aslpo}{\graphof{C}}
}{
  \evalcatchers(\env, \catchers, \some{\vs}, \sm) \evalarrow \withgraph{C}{\vg}
}
\end{mathpar}
\CodeSubsection{\EvalCatchOtherwiseBegin}{\EvalCatchOtherwiseEnd}{../Interpreter.ml}

\SemanticsRuleDef{CatchNone}
\ExampleDef{Evaluation of an Uncaught Exception}
The specification in \listingref{semantics-catchnone} does not print anything.
It shows how a \texttt{try} statement (the inner one) may not have a \texttt{catch} clause
that matches the exception type (\texttt{MyExceptionType1}).
\ASLListing{A catch clause that does not match a thrown exception type}{semantics-catchnone}{\semanticstests/SemanticsRule.CatchNone.asl}

\ProseParagraph
\AllApply
\begin{itemize}
  \item $\sm$ is $\Throwing(\vv, \vvty, \sg, \envthrow)$;
  \item $\env$ consists of the \staticenvironmentterm{} $\tenv$ and dynamic environment $\denv$;
  \item $\envthrow$ consists of the \staticenvironmentterm{} $\tenv$ and dynamic environment \\ $\denvthrow$;
  \item finding the first catcher with the \staticenvironmentterm{} $\tenv$, the exception type $\vvty$,
  and the list of catchers $\catchers$ gives a catcher that declares the name $\name$ and gives $\None$
  (that is, neither of the \texttt{catch} clauses matches the raised exception);
  \item since there no \texttt{otherwise} clause, the result is $\sm$.
\end{itemize}
\FormallyParagraph
\begin{mathpar}
\inferrule{
  \sm \eqname \Throwing(\vv, \vvty, \sg, \envthrow)\\
  \env \eqname (\tenv, \denv)\\
  \findcatcher(\tenv, \vvty, \catchers) = \None
}{
  \evalcatchers(\env, \catchers, \None, \sm) \evalarrow \sm
}
\end{mathpar}
\CodeSubsection{\EvalCatchNoneBegin}{\EvalCatchNoneEnd}{../Interpreter.ml}

\SemanticsRuleDef{CatchNoThrow}
\ExampleDef{Evaluation of a Try Statement that Does Not Raise an Exception}
The specification in \listingref{semantics-nothrow} prints \texttt{No exception raised}.
\ASLListing{A \texttt{try} statement that does not raise an exception}{semantics-nothrow}{\semanticstests/SemanticsRule.CatchNoThrow.asl}

\ProseParagraph
\AllApply
\begin{itemize}
\item $\sm$ is a \Prosenormalconfiguration;
\item \Proseeqdef{$\smnew$}{$\sm$}.
\end{itemize}

\FormallyParagraph
\begin{mathpar}
\inferrule{
  \sm \in \TNormal
}{
  \evalcatchers(\env, \catchers, \Ignore, \sm) \evalarrow \sm
}
\end{mathpar}
\CodeSubsection{\EvalCatchNoThrowBegin}{\EvalCatchNoThrowEnd}{../Interpreter.ml}

\SemanticsRuleDef{FindCatcher}
\hypertarget{def-findcatcher}{}
The (recursively-defined) helper relation
\[
  \findcatcher(\overname{\staticenvs}{\tenv} \aslsep \overname{\ty}{\vvty}, \overname{\KleeneStar{\catcher}}{\catchers})
  \;\aslrel\; \Option(\catcher) \enspace,
\]
returns the first catcher clause in $\catchers$ that matches the type $\vvty$ (as a singleton set), or an empty set ($\None$),
by invoking $\typesat$ with the \staticenvironmentterm{} $\tenv$.

\ExampleDef{Finding a Catch Clause}
In \listingref{annotate-catcher}, the second catch clause --- for the exception type ExceptionType2
is matched for the type of the exception value thrown by \verb|update_and_throw|.

In \listingref{annotate-catcher}, no catch clause is matched for the type of the exception value thrown by \verb|update_and_throw|,
resulting in a \dynamicerrorterm{}.
\ASLListing{Looking for a catch clause and failing to find one}{catcher-not-found}{\typingtests/TypingRule.FindCatcher.None.asl}

\ProseParagraph
\OneApplies
\begin{itemize}
  \item \AllApplyCase{empty}
  \begin{itemize}
    \item $\catchers$ is an empty list;
    \item the result is $\None$.
  \end{itemize}

  \item \AllApplyCase{match}
  \begin{itemize}
    \item $\catchers$ has $\vc$ as its head and $\catchersone$ as its tail;
    \item $\vc$ consists of $(\nameopt, \ety, \vs)$;
    \item $\vvty$ \subtypesterm\ $\ety$ in the \staticenvironmentterm{} $\tenv$;
    \item the result is the singleton set for $\vc$.
  \end{itemize}

  \item \AllApplyCase{no\_match}
  \begin{itemize}
    \item $\catchers$ has $\vc$ as its head and $\catchersone$ as its tail;
    \item $\vc$ consists of $(\nameopt, \ety, \vs)$;
    \item $\vvty$ does not \subtypeterm\ $\ety$ in the \staticenvironmentterm{} $\tenv$;
    \item the result of finding a catcher for $\vvty$ with the type environment $\tenv$ in the tail list $\catchersone$
    is $d$;
    \item the result is $d$.
  \end{itemize}
\end{itemize}

\FormallyParagraph
\begin{mathpar}
\inferrule[empty]{}{\findcatcher(\tenv, \vvty, \overname{\emptylist}{\catchers}) \evalarrow \None}
\end{mathpar}

\begin{mathpar}
\inferrule[match]{
  \catchers = [\vc] \concat \catchersone\\
  \vc \eqname (\nameopt, \ety, \vs) \\
  \subtypes(\tenv, \vvty, \ety)
}{
  \findcatcher(\tenv, \vvty, \catchers) \evalarrow \some{\vc}
}
\end{mathpar}

\begin{mathpar}
\inferrule[no\_match]{
  \catchers = [\vc] \concat \catchersone\\
  \vc \eqname (\nameopt, \ety, \vs) \\
  \neg\subtypes(\tenv, \vvty, \ety)\\
  d \eqdef \findcatcher(\tenv, \vvty, \catchersone)
}{
  \findcatcher(\tenv, \vvty, \catchers) \evalarrow d
}
\end{mathpar}
\CodeSubsection{\EvalFindCatcherBegin}{\EvalFindCatcherEnd}{../Interpreter.ml}

\subsubsection{Comments}
\identr{SPNM}
When the \texttt{catch} of a \texttt{try} statement is executed, then the
thrown exception is caught by the first catcher in that \texttt{catch} which it
type-satisfies or the \texttt{otherwise\_opt} in that catch if it exists.
